import {useEffect,useState} from 'react';
import {ScrollView,Text} from 'react-native';
import * as Location from 'expo-location';
import type {CitizenScan,CitizenResult,ComplaintReceipt} from '../../../shared/contracts';
import {valueText} from '../../../shared/contracts';
import {api} from './api';
import {cache} from './store';
import {Button,Card,Field,Note,s} from './ui';

type CitizenLocation={latitude:number;longitude:number;accuracy_m:number|null;captured_at:string};

export default function Citizen({scan}:{scan:CitizenScan}){
 const [result,setResult]=useState<CitizenResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[brand,setBrand]=useState(''),[manufacturer,setManufacturer]=useState(''),[shop,setShop]=useState(''),[area,setArea]=useState(''),[citizenLocation,setCitizenLocation]=useState<CitizenLocation|null>(null),[corrections,setCorrections]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false),[receipt,setReceipt]=useState<ComplaintReceipt|null>(null);

 async function analyse(){setBusy(true);setError('');try{let r=await api.citizenAnalyse(scan.scan_id);const id=r.analysis_run_id||r.id!;const cfg=scan.analysis_configuration,deadline=Date.now()+cfg.timeout_seconds*1000;while(['QUEUED','RUNNING'].includes(r.status)){if(Date.now()>deadline)throw Error('Your scan is still processing. Retry checking when connected.');await new Promise(resolve=>setTimeout(resolve,cfg.poll_interval_ms));r=await api.citizenAnalysis(id)}if(r.status==='FAILED')throw Error('This scan could not be analysed. Retake unclear images or retry.');setResult(await api.citizenResult(scan.scan_id))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{analyse()},[scan.scan_id]);

 async function useCurrentLocation(){setBusy(true);setError('');try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw Error('Location permission was not granted. Enter the shop location manually or skip location sharing.');const location=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setCitizenLocation({latitude:location.coords.latitude,longitude:location.coords.longitude,accuracy_m:location.coords.accuracy,captured_at:new Date(location.timestamp).toISOString()})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}

 return <ScrollView contentContainerStyle={s.content}><Text style={s.title}>{receipt?'Complaint submitted':'Your preliminary package check'}</Text><Note>These are possible issues from visible declarations. They are not an authoritative legal finding.</Note>{error&&<Text style={s.error}>{error}</Text>}{!receipt&&<Button secondary title={busy?'Checking…':'Refresh preliminary results'} disabled={busy} onPress={analyse}/>} {receipt?<Card><Text style={s.h2}>{receipt.reference}</Text><Text selectable>{receipt.tracking_token}</Text><Text>{receipt.message}</Text><Text>Keep your reference and private tracking token. They are saved on this device for tracking.</Text></Card>:result&&<><Text>{result.notice}</Text>{result.declarations.map((d,i)=><Card key={i}><Text style={s.h2}>{d.declaration}</Text><Text>{valueText(d.value)}</Text><Text>{d.message}</Text></Card>)}<Text style={s.h2}>Confirm the package and shop</Text><Field label="Product name" value={name} onChange={setName}/><Field label="Brand" value={brand} onChange={setBrand}/><Field label="Manufacturer / packer / importer" value={manufacturer} onChange={setManufacturer}/><Field label="Shop / retailer name" value={shop} onChange={setShop}/><Field label="Shop area / location" value={area} onChange={setArea}/><Card><Text style={s.h2}>Current location (optional)</Text><Text>Share the device location to help identify where the product was found, enter the shop location above, or skip this step.</Text><Note>Citizen location is complaint context only. It is not official inspection provenance.</Note>{citizenLocation?<><Text>Location captured · accuracy {citizenLocation.accuracy_m===null?'not reported':Math.round(citizenLocation.accuracy_m)+' m'}</Text><Button secondary title="Remove shared location" onPress={()=>setCitizenLocation(null)}/></>:<Button secondary title="Use current device location" disabled={busy} onPress={useCurrentLocation}/>}</Card>{result.declarations.map(d=><Field key={d.declaration} label={'Correction, if needed: '+d.declaration} value={corrections[d.declaration]||''} onChange={text=>setCorrections(old=>({...old,[d.declaration]:text}))}/>)}<Button secondary title={confirmed?'✓ I have checked and confirmed these details':'I have checked and confirm these details'} onPress={()=>setConfirmed(!confirmed)}/><Button title="Submit structured complaint" disabled={!confirmed||busy||!name.trim()||shop.trim().length<2} onPress={async()=>{setBusy(true);setError('');try{const r=await api.complaint({scan_id:scan.scan_id,product_snapshot:{product_name:name,brand,manufacturer,package_family:scan.package_family},shop_name:shop,shop_location:{area,citizen_supplied_location:citizenLocation},declaration_corrections:corrections,confirmed:true});await cache('complaint',r);setReceipt(r)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/></>}</ScrollView>
}
