import tokens from '../../../shared/design-tokens/tokens.json';
import {Pressable,Text,TextInput,View,StyleSheet} from 'react-native';import type {ReactNode} from 'react';
export const colors={...tokens.colors,nav:tokens.colors.institutional};
export function Button({title,onPress,disabled=false,secondary=false}:{title:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,{backgroundColor:secondary?'white':colors.action,opacity:disabled?.45:1}]}><Text style={{color:secondary?colors.action:'white',fontWeight:'700',fontSize:16,textAlign:'center'}}>{title}</Text></Pressable>}
export function Field({label,value,onChange,secure=false,multiline=false}:{label:string;value:string;onChange:(s:string)=>void;secure?:boolean;multiline?:boolean}){return <View style={{gap:6}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={[s.input,multiline&&{minHeight:100,textAlignVertical:'top'}]} value={value} onChangeText={onChange} secureTextEntry={secure} multiline={multiline} autoCapitalize={secure?'none':'sentences'}/></View>}
export function Tag({status}:{status:string}){const colour=status==='SUPPORTED'?colors.evidence:['ACCEPTED','CORRECTED','COMPLETED','READY','APPROVED'].includes(status)?colors.verified:status==='FAILED'?colors.failure:colors.muted;return <Text accessibilityLabel={status} style={{color:colour,fontWeight:'700',fontSize:13}}>● {status.replaceAll('_',' ')}</Text>}
export function Card({children}:{children:ReactNode}){return <View style={s.card}>{children}</View>}
export function Note({children}:{children:ReactNode}){return <Text style={s.note}>{children}</Text>}
export const s=StyleSheet.create({body:{flex:1,backgroundColor:colors.canvas},content:{padding:18,gap:16,paddingBottom:48},header:{padding:18,backgroundColor:colors.nav,gap:4},title:{fontSize:26,fontWeight:'700',color:colors.text},h2:{fontSize:20,fontWeight:'700',color:colors.text},text:{fontSize:16,lineHeight:24,color:colors.text},label:{fontSize:14,fontWeight:'600',color:colors.text},input:{borderWidth:1,borderColor:colors.border,borderRadius:8,padding:13,minHeight:48,fontSize:16,backgroundColor:'white',color:colors.text},button:{minHeight:50,borderRadius:8,borderWidth:1,borderColor:colors.action,padding:14,justifyContent:'center'},card:{backgroundColor:'white',borderWidth:1,borderColor:colors.border,borderRadius:8,padding:16,gap:12},note:{fontSize:14,lineHeight:21,color:colors.attention,padding:12,backgroundColor:'#FFF8E8',borderRadius:6},error:{fontSize:15,lineHeight:22,color:colors.failure},row:{flexDirection:'row',gap:10,alignItems:'center',flexWrap:'wrap'}});
