'use client';
import {useState} from 'react';
import {X} from 'lucide-react';
import {api} from '../lib/api';
import type {Brief,CopilotAnswer} from '../../../../shared/contracts';
import {ErrorBox,Status,Notice} from './ui';
export default function CopilotPanel({context,onClose,onBrief}:{context:{kind:'case'|'pattern';id:string;title:string};onClose:()=>void;onBrief:(brief:Brief)=>void}){
 const [answer,setAnswer]=useState<CopilotAnswer|null>(null),[brief,setBrief]=useState<Brief|null>(null),[content,setContent]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(work:()=>Promise<void>){setBusy(true);setError('');try{await work()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function save(b:Brief){setBrief(b);setContent(b.content);onBrief(b)}
 return <aside className="copilot-drawer" aria-label="Contextual Copilot"><div className="panel-head"><div><h2>Contextual assistance</h2><small>{context.title}</small></div><button className="icon-button" aria-label="Close assistance" onClick={onClose}><X/></button></div><div className="panel-body stack"><Notice>Answers use permitted records. Drafts require separate officer approval.</Notice>{error&&<ErrorBox error={error}/>}<div className="actions">{[['SUMMARY','Summarise'],['PRIORITY','Explain priority'],['RELATED','Related verified cases'],['GAPS','Evidence gaps']].map(([key,label])=><button className="btn small" key={key} disabled={busy} onClick={()=>run(async()=>setAnswer(await api.copilot(context.kind,context.id,key)))}>{label}</button>)}</div>{answer&&<><p>{answer.answer}</p>{answer.evidence_gap&&<Notice>{answer.evidence_gap}</Notice>}{answer.source_cards.map((s,i)=><div key={i} className="detail-row"><strong>{s.title}</strong><p><Status value={s.verification_label}/></p><small>{s.source_type} · {s.source_id}</small></div>)}</>}<button className="btn" disabled={busy} onClick={()=>run(async()=>save(await api.brief(context.kind,context.id)))}>Prepare persisted inspection brief</button>{brief&&<><Status value={brief.status}/><label>Brief content<textarea rows={12} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="btn" disabled={busy} onClick={()=>run(async()=>save(await api.brief(context.kind,context.id,brief.id,content)))}>Save edited draft</button><label>Approval / rejection reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="actions">{(['APPROVE','REJECT'] as const).map(decision=><button key={decision} className="btn" disabled={busy||brief.status!=='DRAFT'||!reason.trim()||content!==brief.content} onClick={()=>run(async()=>save(await api.approveBrief(brief.id,decision,reason)))}>{decision} brief</button>)}</div><p>Approval records your decision. Assign work separately in the case operations panel.</p></>}</div></aside>
}
