'use client';
import {useState} from 'react';
import {api} from '../lib/api';
import {valueText,type Action,type SourceRef,type Value} from '../../../../shared/contracts';
import {useResource,Loading,ErrorBox,Empty,Status,Notice} from './ui';
export default function EvidenceWorkbench({caseId,canVerify=false}:{caseId:string;canVerify?:boolean}){
 const r=useResource(()=>api.map(caseId),caseId);const [selected,setSelected]=useState(0),[source,setSource]=useState(0),[reason,setReason]=useState(''),[correction,setCorrection]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const d=r.data?.items[selected];const s=d?.source_refs[source];
 async function review(action:Action,findingId?:string){if(!d)return;setBusy(true);setError('');try{const value:Value|undefined=action==='CORRECT'?JSON.parse(correction):undefined;if(findingId)await api.verify(findingId,action,reason,value);else await api.reviewDeclaration(caseId,d.declaration_group,action,reason,d.source_refs,value);r.reload();setReason('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(r.loading)return <Loading/>;if(r.error)return <ErrorBox error={r.error} retry={r.reload}/>;if(!d)return <Empty title="Analysis not available" detail="Capture and synchronise evidence, then run analysis from the Inspector app."/>;
 return <div className="panel-body"><Notice>Source-supported evidence and officer-verified findings are separate decisions.</Notice>{error&&<ErrorBox error={error}/>}<div className="split"><nav aria-label="Declaration map" className="stack">{r.data!.items.map((item,i)=><button className={`btn ${i===selected?'primary':''}`} key={item.id} onClick={()=>{setSelected(i);setSource(0);setCorrection(JSON.stringify(item.reviewed_value||item.fused_value||{},null,2))}} style={{textAlign:'left',display:'block'}}><strong>{item.title}</strong><p>{valueText(item.reviewed_value||item.fused_value)}</p><Status value={item.evidence_state}/><p>{item.source_refs.length} sources · {item.verification_status}</p><small>{item.next_capture_prompt||'Review source and declaration'}</small></button>)}</nav><section className="stack"><h2>{d.title}</h2><Status value={d.evidence_state}/><p>{valueText(d.reviewed_value||d.fused_value)}</p>{d.source_refs.length>0?<><label>Source image<select value={source} onChange={e=>setSource(Number(e.target.value))}>{d.source_refs.map((ref,i)=><option key={`${ref.evidence_id}-${i}`} value={i}>Source {i+1} · {ref.extractor||ref.source_type||'Package evidence'}</option>)}</select></label>{s&&<SourceImage source={s}/>}</>:<Notice>No source established. Return to field capture before reviewing this declaration.</Notice>}
 {s&&<div className="detail-row"><strong>OCR candidate</strong><p>{s.raw_text||'Inspected region'}</p><small>{s.confidence!==undefined?`Confidence ${Math.round(s.confidence*100)}% · `:''}{s.extractor}</small><p className="mono">SHA-256: {s.provenance?.sha256||'See evidence record'}</p></div>}
 {Object.entries(d.presentation).map(([key,p])=><div key={key}><strong>{key}</strong> <Status value={p.presentation_state}/><p>{p.explanation}</p></div>)}
 {canVerify&&<><label>Decision reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain your source review"/></label><label>Corrected declaration fields (JSON)<textarea value={correction} onChange={e=>setCorrection(e.target.value)} placeholder={JSON.stringify(d.fused_value||{})}/></label><h3>Declaration evidence review</h3><div className="actions">{(['ACCEPT','CORRECT','REJECT'] as Action[]).map(a=><button className="btn" disabled={busy||!reason.trim()||!d.source_refs.length} key={a} onClick={()=>review(a)}>{a==='ACCEPT'?'Confirm value':a==='CORRECT'?'Correct value':'Mark unresolved'}</button>)}</div>
 </>}<h3>Deterministic rule results</h3>{d.applicable_rules.map(rule=><div className="detail-row" key={rule.id}><strong>{rule.rule_code} · {rule.rule_version}</strong> <Status value={rule.result_state}/><p>{rule.explanation}</p><small>{rule.legal_reference}</small></div>)}<h3>Finding verification</h3>{d.findings.length===0?<p>No potential finding has been created.</p>:d.findings.map(f=><div className="detail-row" key={f.id}><Status value={f.status}/><p>{f.rule_code}: {f.explanation}</p>{canVerify&&f.status==='POTENTIAL'&&<div className="actions">{(['ACCEPT','CORRECT','REJECT'] as Action[]).map(a=><button className="btn" key={a} disabled={busy||!reason.trim()} onClick={()=>review(a,f.id)}>{a}</button>)}</div>}</div>)}
 </section></div></div>
}
export function SourceImage({source}:{source:SourceRef}){const [x1,y1,x2,y2]=source.bbox;return <figure><div style={{position:'relative',lineHeight:0}}><img src={api.evidenceUrl(source.evidence_id)} alt="Original package evidence with selected declaration region" style={{width:'100%',height:'auto'}}/><span aria-label="Selected source bounding box" style={{position:'absolute',left:`${x1*100}%`,top:`${y1*100}%`,width:`${(x2-x1)*100}%`,height:`${(y2-y1)*100}%`,border:'3px solid #0F6B6D',background:'rgba(15,107,109,.07)'}}/></div><figcaption>Original evidence · {source.evidence_id}</figcaption></figure>}
