import './global.css';
import {useEffect,useState} from 'react';
import {ActivityIndicator,BackHandler,KeyboardAvoidingView,Platform,ScrollView,Text,View} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import NetInfo from '@react-native-community/netinfo';
import {api,baseUrl} from './src/api';
import {initStore,setToken,cache,cached,localAssignments,rememberAssignment,rememberInspector,unlockInspector} from './src/store';
import {Button,Field,Card,Note,s} from './src/ui';
import type {DownloadedAssignment,CitizenScan,PackageFamily,Followup} from '../../shared/contracts';
import Capture from './src/Capture';import Inspection from './src/Inspection';import Citizen from './src/Citizen';
export default function App(){const [ready,setReady]=useState(false),[fatal,setFatal]=useState('');useEffect(()=>{initStore().then(()=>setReady(true)).catch(e=>setFatal(e.message))},[]);return <SafeAreaProvider><SafeAreaView style={s.body}>{fatal?<View style={s.content}><Text style={s.error}>{fatal}</Text></View>:ready?<Workspace/>:<ActivityIndicator accessibilityLabel="Opening protected local storage"/>}</SafeAreaView></SafeAreaProvider>}
function Workspace(){const [screen,setScreen]=useState('entry'),[online,setOnline]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState('inspector@emaap.demo'),[password,setPassword]=useState(''),[assignments,setAssignments]=useState<DownloadedAssignment[]>([]),[active,setActive]=useState<DownloadedAssignment|null>(null),[scan,setScan]=useState<CitizenScan|null>(null),[family,setFamily]=useState<PackageFamily>('RIGID_CUBOID'),[product,setProduct]=useState(''),[followups,setFollowups]=useState<Followup[]>([]);
 useEffect(()=>NetInfo.addEventListener(n=>setOnline(Boolean(n.isConnected))),[]);useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(screen==='entry')return false;setScreen(screen==='capture'&&active?'inspection':'entry');return true});return()=>sub.remove()},[screen,active]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function loadAssignments(){const list=await api.assignments();const downloaded:DownloadedAssignment[]=[];for(const entry of list.items){const capture=await api.plan(entry.case.id);downloaded.push({assignment:entry.assignment,case:entry.case,capture})}setAssignments(downloaded);setFollowups(list.followups);setScreen('assignments')}
 const home=()=>{setScreen('entry');setActive(null);setScan(null);setError('')};
 return <KeyboardAvoidingView className="flex-1" style={s.body} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Text style={{color:'white',fontSize:22,fontWeight:'700'}}>e-Maap</Text><Text style={{color:'#DCE7F0'}}>Measure Compliance. Protect Consumers.</Text><Text style={{color:online?'#DAEBE7':'#FFE3A4',marginTop:5}}>● {online?'Connected':'Offline · evidence stays on this device'}</Text></View>{screen!=='entry'&&<View style={{paddingHorizontal:18,paddingTop:8}}><Button title="‹ Main menu" secondary onPress={home}/></View>}{error&&<Text accessibilityRole="alert" style={[s.error,{padding:18}]}>{error}</Text>}{busy&&<ActivityIndicator/>}
 {screen==='capture'&&(active||scan)?<Capture caseId={active?.case.id||scan!.scan_id} plan={active?.capture} scan={scan||undefined} inspector={Boolean(active)} online={online} onDone={()=>setScreen(active?'inspection':'citizen-result')}/>:screen==='inspection'&&active?<Inspection assignment={active} online={online} onCapture={()=>setScreen('capture')}/>:screen==='citizen-result'&&scan?<Citizen scan={scan}/>:<ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {screen==='entry'&&<><Text style={s.title}>Check a package. Know your next step.</Text><Card><Text style={s.h2}>For citizens</Text><Text style={s.text}>Scan declarations and submit a structured concern. Results are preliminary.</Text><Button title="Check a package" disabled={!online||busy} onPress={()=>run(async()=>{const session=await api.citizenSession();await setToken(session.access_token);setScreen('citizen-start')})}/><Button secondary title="Track a complaint" disabled={!online||busy} onPress={()=>run(async()=>{const session=await api.citizenSession();await setToken(session.access_token);setScreen('tracking')})}/></Card><Card><Text style={s.h2}>Inspector field operations</Text><Text style={s.text}>Assignments, capture, evidence review and reports.</Text><Button title="Inspector sign in" onPress={()=>setScreen('login')}/><Button secondary title="Open downloaded work offline" onPress={()=>setScreen('login')}/></Card><Text style={{fontSize:12}}>Backend: {baseUrl}</Text></>}
 {screen==='login'&&<><Text style={s.title}>Inspector sign in</Text><Field label="Email" value={email} onChange={setEmail}/><Field label="Password" value={password} onChange={setPassword} secure/><Button title="Sign in & download assignments" disabled={busy} onPress={()=>run(async()=>{if(!online){const id=await unlockInspector(email,password);setAssignments((await localAssignments()).filter((a):a is DownloadedAssignment=>Boolean(a)&&a!.assignment.inspector_id===id));setScreen('assignments');setPassword('');return}const user=await api.login(email,password);if(user.role!=='INSPECTOR')throw Error('Use an Inspector account for field operations.');await setToken(user.access_token);await rememberInspector(email,password,user);await loadAssignments();setPassword('')})}/><Note>Demo only: inspector@emaap.demo / EmaapDemo!2026</Note></>}
 {screen==='assignments'&&<><Text style={s.title}>Your assignments</Text><Button secondary title="Refresh from server" disabled={!online||busy} onPress={()=>run(loadAssignments)}/>{assignments.length===0&&<Text>No downloaded assignments.</Text>}{followups.map(f=><FollowupCard key={f.id} f={f} online={online}/>)}{assignments.map(a=><Card key={a.assignment.id}><Text style={s.h2}>{a.case.product_snapshot.product_name}</Text><Text>{a.case.reference} · {a.case.shop.name}</Text><Text>{a.case.status}</Text><Button title="Open assignment" onPress={()=>run(async()=>{const opened=online?await api.downloadAssignment(a.assignment.id):a;if(online){await rememberAssignment(opened);const detail=await api.case(a.case.id);await cache('sequence-base:'+a.case.id,Math.max(0,...detail.evidence.map(e=>e.sequence_no)))}setActive(opened);setScreen('inspection')})}/></Card>)}</>}
 {screen==='citizen-start'&&<><Text style={s.title}>About this package</Text><Field label="Product name" value={product} onChange={setProduct}/><Text style={s.h2}>Choose its shape</Text>{(['RIGID_CUBOID','CURVED_RIGID','FLEXIBLE'] as PackageFamily[]).map(f=><Button key={f} title={(family===f?'✓ ':'')+f.replaceAll('_',' ')} secondary={family!==f} onPress={()=>setFamily(f)}/>)}<Button title="Start guided scan" disabled={busy||!online} onPress={()=>run(async()=>{setScan(await api.scan(family,product));setActive(null);setScreen('capture')})}/></>}
 {screen==='tracking'&&<Tracking/>}
 </ScrollView>}</KeyboardAvoidingView>
}
function Tracking(){const [reference,setReference]=useState(''),[token,setToken]=useState(''),[result,setResult]=useState('');useEffect(()=>{cached<{reference:string;tracking_token:string}>('complaint').then(r=>{if(r){setReference(r.reference);setToken(r.tracking_token)}})},[]);return <><Text style={s.title}>Track your complaint</Text><Field label="Reference" value={reference} onChange={setReference}/><Field label="Private tracking token" value={token} onChange={setToken}/><Button title="Check status" onPress={async()=>{try{const r=await api.track(reference,token);setResult(r.status)}catch(e){setResult((e as Error).message)}}}/><Text>{result}</Text></>}
function FollowupCard({f,online}:{f:Followup;online:boolean}){const [status,setStatus]=useState(f.status),[note,setNote]=useState(''),[error,setError]=useState('');return <Card><Text style={s.h2}>Assigned follow-up</Text><Text>{f.note}</Text><Text>{status.replaceAll('_',' ')}</Text>{status!=='COMPLETED'&&<><Field label="Progress note" value={note} onChange={setNote}/><Button title={status==='ASSIGNED'?'Start follow-up':'Complete follow-up'} disabled={!online||!note.trim()} onPress={async()=>{try{const r=await api.updateFollowup(f.id,status==='ASSIGNED'?'IN_PROGRESS':'COMPLETED',note);setStatus(r.status)}catch(e){setError((e as Error).message)}}}/></>}{error&&<Text style={s.error}>{error}</Text>}</Card>}
